/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "n7.1.1-7-gd9b45767c8-20250503"
#endif /* AVUTIL_FFVERSION_H */
