/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "n7.1-18-g5120d30890-20241111"
#endif /* AVUTIL_FFVERSION_H */
